### ISSUE TITLE
Cran submission checklist

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/extras#64]
# CRAN submission checklist

- [x] All tests pass & no warnings, notes or messages in check
- [x] Close stale issues
- [x] Lifecycle badge cannot be experimental
- [x] Copyright holder is listed 
- [x] No "in R" or "with R" in the title
- [x] Title is in title case
- [x] No "This package" in package name, title or description
- [x] DESCRIPTION file is filled out
- [x] Use paraentheses after function name
- [x] Add `if (interative()) {}` to truely ensure an example does not run
- [x] Slow examples should be wrapped in `\donttest{}`
- [x] Check URLs and links
- [x] Check spelling 
- [x] Run R CMD Checks on various operating systems and R versions
- [x] Check reverse dependencies
- [x] Bump and tag version
- [x] NEWS.md file is updated
- [x] Update cran-commits.md file
